[mgr]
show_hidden = true

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*",  block = true, for = "windows" },
]
open= [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*",  block = true, for = "windows" },
]
